image: gradle:6.1.1-jdk13

stages:
  - build
  - test

build:
  stage: build
  script: gradle build -x test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - assignment*/build
      - .gradle

checkstyle:a1:
  stage: test
  script: gradle :assignment1:checkstyleMain :assignment1:checkstyleTest
  allow_failure: true
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - assignment1/build
      - .gradle

test:a1:
  stage: test
  script: gradle :assignment1:test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - assignment1/build
      - .gradle
  artifacts:
    paths:
      - assignment1
    when: always
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "DDP2-CSUI/2020"'

test:a2:
  stage: test
  script: gradle :assignment2:test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - assignment2/build
      - .gradle
  artifacts:
    paths:
      - assignment2
    when: always
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "DDP2-CSUI/2020"'

diff:a2:
  stage: test
  script:
    - "gradle :assignment2:run --console plain --quiet < assignment2/testcases/in1.txt | diff assignment2/testcases/out1.txt -"
    - "gradle :assignment2:run --console plain --quiet < assignment2/testcases/in2.txt | diff assignment2/testcases/out2.txt -"
  allow_failure: true
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - assignment2/build
      - .gradle
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "DDP2-CSUI/2020"'
