image: gradle:6.1.1-jdk13

stages:
  - build
  - test

build:
  stage: build
  script: gradle build -x test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - assignment*/build
      - assignment*/.gradle

checkstyle:a1:
  stage: test
  script: gradle checkstyleMain checkstyleTest
  allow_failure: true
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - assignment1/build
      - assignment1/.gradle

test:a1:
  stage: test
  script: gradle :assignment-1:test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - assignment1/build
      - assignment1/.gradle
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "DDP2-CSUI/2020"'
