image: gradle:6.1.1-jdk13

stages:
  - build
  - test

build:
  stage: build
  script: gradle build -x test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - assignment*/build
      - .gradle

checkstyle:a1:
  stage: test
  script: gradle :assignment1:checkstyleMain :assignment1:checkstyleTest
  allow_failure: true
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - assignment1/build
      - .gradle

test:a1:
  stage: test
  script: gradle :assignment1:test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - assignment1/build
      - .gradle
  artifacts:
    paths:
      - assignment1
    when: always
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "DDP2-CSUI/2020"'
